import SwiftUI
import Foundation

struct Background: View {
    let opacity = 0.4
    
    var body: some View {
        ZStack {
            Colors.background
                .ignoresSafeArea()
            HStack {
                VStack {
                    Image(systemName: "hand.thumbsup")
                        .resizable()
                        .foregroundStyle(.black)
                        .scaledToFit()
                        .frame(width: 50)
                        .opacity(opacity)
                        .padding(35)
                    Image(systemName: "hand.raised")
                        .resizable()
                        .foregroundStyle(.black)
                        .scaledToFit()
                        .frame(width: 50)
                        .opacity(opacity)
                        .padding(35)
                    Image(systemName: "hand.point.left")
                        .resizable()
                        .foregroundStyle(.black)
                        .scaledToFit()
                        .frame(width: 50)
                        .opacity(opacity)
                        .padding(35)
                    Image(systemName: "hand.draw")
                        .resizable()
                        .foregroundStyle(.black)
                        .scaledToFit()
                        .frame(width: 50)
                        .opacity(opacity)
                        .padding(35)
                    Image(systemName: "hand.wave")
                        .resizable()
                        .foregroundStyle(.black)
                        .scaledToFit()
                        .frame(width: 50)
                        .opacity(opacity)
                        .padding(35)
                    Image(systemName: "hand.point.up.braille")
                        .resizable()
                        .foregroundStyle(.black)
                        .scaledToFit()
                        .frame(width: 50)
                        .opacity(opacity)
                        .padding(35)
                }
                VStack {
                    Image(systemName: "hand.tap")
                        .resizable()
                        .foregroundStyle(.black)
                        .scaledToFit()
                        .frame(width: 50)
                        .opacity(opacity)
                        .padding(35)
                    Image(systemName: "hand.raised.fingers.spread")
                        .resizable()
                        .foregroundStyle(.black)
                        .scaledToFit()
                        .frame(width: 50)
                        .opacity(opacity)
                        .padding(35)
                    Image(systemName: "hands.clap")
                        .resizable()
                        .foregroundStyle(.black)
                        .scaledToFit()
                        .frame(width: 50)
                        .opacity(opacity)
                        .padding(35)
                    Image(systemName: "hand.thumbsdown")
                        .resizable()
                        .foregroundStyle(.black)
                        .scaledToFit()
                        .frame(width: 50)
                        .opacity(opacity)
                        .padding(35)
                    Image(systemName: "hand.point.right")
                        .resizable()
                        .foregroundStyle(.black)
                        .scaledToFit()
                        .frame(width: 50)
                        .opacity(opacity)
                        .padding(35)
                    Image(systemName: "hand.thumbsup.circle")
                        .resizable()
                        .foregroundStyle(.black)
                        .scaledToFit()
                        .frame(width: 50)
                        .opacity(opacity)
                        .padding(35)
                }.offset(y: 65)
                VStack {
                    Image(systemName: "hand.thumbsup")
                        .resizable()
                        .foregroundStyle(.black)
                        .scaledToFit()
                        .frame(width: 50)
                        .opacity(opacity)
                        .padding(35)
                    Image(systemName: "hand.raised")
                        .resizable()
                        .foregroundStyle(.black)
                        .scaledToFit()
                        .frame(width: 50)
                        .opacity(opacity)
                        .padding(35)
                    Image(systemName: "hand.point.left")
                        .resizable()
                        .foregroundStyle(.black)
                        .scaledToFit()
                        .frame(width: 50)
                        .opacity(opacity)
                        .padding(35)
                    Image(systemName: "hand.draw")
                        .resizable()
                        .foregroundStyle(.black)
                        .scaledToFit()
                        .frame(width: 50)
                        .opacity(opacity)
                        .padding(35)
                    Image(systemName: "hand.wave")
                        .resizable()
                        .foregroundStyle(.black)
                        .scaledToFit()
                        .frame(width: 50)
                        .opacity(opacity)
                        .padding(35)
                    Image(systemName: "hand.point.up.braille")
                        .resizable()
                        .foregroundStyle(.black)
                        .scaledToFit()
                        .frame(width: 50)
                        .opacity(opacity)
                        .padding(35)
                }
                VStack {
                    Image(systemName: "hand.tap")
                        .resizable()
                        .foregroundStyle(.black)
                        .scaledToFit()
                        .frame(width: 50)
                        .opacity(opacity)
                        .padding(35)
                    Image(systemName: "hand.raised.fingers.spread")
                        .resizable()
                        .foregroundStyle(.black)
                        .scaledToFit()
                        .frame(width: 50)
                        .opacity(opacity)
                        .padding(35)
                    Image(systemName: "hands.clap")
                        .resizable()
                        .foregroundStyle(.black)
                        .scaledToFit()
                        .frame(width: 50)
                        .opacity(opacity)
                        .padding(35)
                    Image(systemName: "hand.thumbsdown")
                        .resizable()
                        .foregroundStyle(.black)
                        .scaledToFit()
                        .frame(width: 50)
                        .opacity(opacity)
                        .padding(35)
                    Image(systemName: "hand.point.right")
                        .resizable()
                        .foregroundStyle(.black)
                        .scaledToFit()
                        .frame(width: 50)
                        .opacity(opacity)
                        .padding(35)
                    Image(systemName: "hand.thumbsup.circle")
                        .resizable()
                        .foregroundStyle(.black)
                        .scaledToFit()
                        .frame(width: 50)
                        .opacity(opacity)
                        .padding(35)
                }.offset(y: 65)
                VStack {
                    Image(systemName: "hand.thumbsup")
                        .resizable()
                        .foregroundStyle(.black)
                        .scaledToFit()
                        .frame(width: 50)
                        .opacity(opacity)
                        .padding(35)
                    Image(systemName: "hand.raised")
                        .resizable()
                        .foregroundStyle(.black)
                        .scaledToFit()
                        .frame(width: 50)
                        .opacity(opacity)
                        .padding(35)
                    Image(systemName: "hand.point.left")
                        .resizable()
                        .foregroundStyle(.black)
                        .scaledToFit()
                        .frame(width: 50)
                        .opacity(opacity)
                        .padding(35)
                    Image(systemName: "hand.draw")
                        .resizable()
                        .foregroundStyle(.black)
                        .scaledToFit()
                        .frame(width: 50)
                        .opacity(opacity)
                        .padding(35)
                    Image(systemName: "hand.wave")
                        .resizable()
                        .foregroundStyle(.black)
                        .scaledToFit()
                        .frame(width: 50)
                        .opacity(opacity)
                        .padding(35)
                    Image(systemName: "hand.point.up.braille")
                        .resizable()
                        .foregroundStyle(.black)
                        .scaledToFit()
                        .frame(width: 50)
                        .opacity(opacity)
                        .padding(35)
                }
                VStack {
                    Image(systemName: "hand.tap")
                        .resizable()
                        .foregroundStyle(.black)
                        .scaledToFit()
                        .frame(width: 50)
                        .opacity(opacity)
                        .padding(35)
                    Image(systemName: "hand.raised.fingers.spread")
                        .resizable()
                        .foregroundStyle(.black)
                        .scaledToFit()
                        .frame(width: 50)
                        .opacity(opacity)
                        .padding(35)
                    Image(systemName: "hands.clap")
                        .resizable()
                        .foregroundStyle(.black)
                        .scaledToFit()
                        .frame(width: 50)
                        .opacity(opacity)
                        .padding(35)
                    Image(systemName: "hand.thumbsdown")
                        .resizable()
                        .foregroundStyle(.black)
                        .scaledToFit()
                        .frame(width: 50)
                        .opacity(opacity)
                        .padding(35)
                    Image(systemName: "hand.point.right")
                        .resizable()
                        .foregroundStyle(.black)
                        .scaledToFit()
                        .frame(width: 50)
                        .opacity(opacity)
                        .padding(35)
                    Image(systemName: "hand.thumbsup.circle")
                        .resizable()
                        .foregroundStyle(.black)
                        .scaledToFit()
                        .frame(width: 50)
                        .opacity(opacity)
                        .padding(35)
                }.offset(y: 65)
                VStack {
                    Image(systemName: "hand.thumbsup")
                        .resizable()
                        .foregroundStyle(.black)
                        .scaledToFit()
                        .frame(width: 50)
                        .opacity(opacity)
                        .padding(35)
                    Image(systemName: "hand.raised")
                        .resizable()
                        .foregroundStyle(.black)
                        .scaledToFit()
                        .frame(width: 50)
                        .opacity(opacity)
                        .padding(35)
                    Image(systemName: "hand.point.left")
                        .resizable()
                        .foregroundStyle(.black)
                        .scaledToFit()
                        .frame(width: 50)
                        .opacity(opacity)
                        .padding(35)
                    Image(systemName: "hand.draw")
                        .resizable()
                        .foregroundStyle(.black)
                        .scaledToFit()
                        .frame(width: 50)
                        .opacity(opacity)
                        .padding(35)
                    Image(systemName: "hand.wave")
                        .resizable()
                        .foregroundStyle(.black)
                        .scaledToFit()
                        .frame(width: 50)
                        .opacity(opacity)
                        .padding(35)
                    Image(systemName: "hand.point.up.braille")
                        .resizable()
                        .foregroundStyle(.black)
                        .scaledToFit()
                        .frame(width: 50)
                        .opacity(opacity)
                        .padding(35)
                }
                VStack {
                    Image(systemName: "hand.tap")
                        .resizable()
                        .foregroundStyle(.black)
                        .scaledToFit()
                        .frame(width: 50)
                        .opacity(opacity)
                        .padding(35)
                    Image(systemName: "hand.raised.fingers.spread")
                        .resizable()
                        .foregroundStyle(.black)
                        .scaledToFit()
                        .frame(width: 50)
                        .opacity(opacity)
                        .padding(35)
                    Image(systemName: "hands.clap")
                        .resizable()
                        .foregroundStyle(.black)
                        .scaledToFit()
                        .frame(width: 50)
                        .opacity(opacity)
                        .padding(35)
                    Image(systemName: "hand.thumbsdown")
                        .resizable()
                        .foregroundStyle(.black)
                        .scaledToFit()
                        .frame(width: 50)
                        .opacity(opacity)
                        .padding(35)
                    Image(systemName: "hand.point.right")
                        .resizable()
                        .foregroundStyle(.black)
                        .scaledToFit()
                        .frame(width: 50)
                        .opacity(opacity)
                        .padding(35)
                    Image(systemName: "hand.thumbsup.circle")
                        .resizable()
                        .foregroundStyle(.black)
                        .scaledToFit()
                        .frame(width: 50)
                        .opacity(opacity)
                        .padding(35)
                }.offset(y: 65)
                VStack {
                    Image(systemName: "hand.thumbsup")
                        .resizable()
                        .foregroundStyle(.black)
                        .scaledToFit()
                        .frame(width: 50)
                        .opacity(opacity)
                        .padding(35)
                    Image(systemName: "hand.raised")
                        .resizable()
                        .foregroundStyle(.black)
                        .scaledToFit()
                        .frame(width: 50)
                        .opacity(opacity)
                        .padding(35)
                    Image(systemName: "hand.point.left")
                        .resizable()
                        .foregroundStyle(.black)
                        .scaledToFit()
                        .frame(width: 50)
                        .opacity(opacity)
                        .padding(35)
                    Image(systemName: "hand.draw")
                        .resizable()
                        .foregroundStyle(.black)
                        .scaledToFit()
                        .frame(width: 50)
                        .opacity(opacity)
                        .padding(35)
                    Image(systemName: "hand.wave")
                        .resizable()
                        .foregroundStyle(.black)
                        .scaledToFit()
                        .frame(width: 50)
                        .opacity(opacity)
                        .padding(35)
                    Image(systemName: "hand.point.up.braille")
                        .resizable()
                        .foregroundStyle(.black)
                        .scaledToFit()
                        .frame(width: 50)
                        .opacity(opacity)
                        .padding(35)
                }
            }
        }.ignoresSafeArea()
    }
}

#Preview {
    Background()
}
